<?xml version="1.0" encoding="UTF-8" ?>
<Package name="pepper_tweet" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="__init__" src="pythonlib/oauthlib/__init__.py" />
        <File name="common" src="pythonlib/oauthlib/common.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth1/__init__.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth1/rfc5849/__init__.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/__init__.py" />
        <File name="access_token" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/access_token.py" />
        <File name="authorization" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/authorization.py" />
        <File name="base" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/base.py" />
        <File name="pre_configured" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/pre_configured.py" />
        <File name="request_token" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/request_token.py" />
        <File name="resource" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/resource.py" />
        <File name="signature_only" src="pythonlib/oauthlib/oauth1/rfc5849/endpoints/signature_only.py" />
        <File name="errors" src="pythonlib/oauthlib/oauth1/rfc5849/errors.py" />
        <File name="parameters" src="pythonlib/oauthlib/oauth1/rfc5849/parameters.py" />
        <File name="request_validator" src="pythonlib/oauthlib/oauth1/rfc5849/request_validator.py" />
        <File name="signature" src="pythonlib/oauthlib/oauth1/rfc5849/signature.py" />
        <File name="utils" src="pythonlib/oauthlib/oauth1/rfc5849/utils.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth2/__init__.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth2/rfc6749/__init__.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth2/rfc6749/clients/__init__.py" />
        <File name="backend_application" src="pythonlib/oauthlib/oauth2/rfc6749/clients/backend_application.py" />
        <File name="base" src="pythonlib/oauthlib/oauth2/rfc6749/clients/base.py" />
        <File name="legacy_application" src="pythonlib/oauthlib/oauth2/rfc6749/clients/legacy_application.py" />
        <File name="mobile_application" src="pythonlib/oauthlib/oauth2/rfc6749/clients/mobile_application.py" />
        <File name="service_application" src="pythonlib/oauthlib/oauth2/rfc6749/clients/service_application.py" />
        <File name="web_application" src="pythonlib/oauthlib/oauth2/rfc6749/clients/web_application.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/__init__.py" />
        <File name="authorization" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/authorization.py" />
        <File name="base" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/base.py" />
        <File name="pre_configured" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/pre_configured.py" />
        <File name="resource" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/resource.py" />
        <File name="revocation" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/revocation.py" />
        <File name="token" src="pythonlib/oauthlib/oauth2/rfc6749/endpoints/token.py" />
        <File name="errors" src="pythonlib/oauthlib/oauth2/rfc6749/errors.py" />
        <File name="__init__" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/__init__.py" />
        <File name="authorization_code" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py" />
        <File name="base" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/base.py" />
        <File name="client_credentials" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/client_credentials.py" />
        <File name="implicit" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/implicit.py" />
        <File name="refresh_token" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py" />
        <File name="resource_owner_password_credentials" src="pythonlib/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py" />
        <File name="parameters" src="pythonlib/oauthlib/oauth2/rfc6749/parameters.py" />
        <File name="request_validator" src="pythonlib/oauthlib/oauth2/rfc6749/request_validator.py" />
        <File name="tokens" src="pythonlib/oauthlib/oauth2/rfc6749/tokens.py" />
        <File name="utils" src="pythonlib/oauthlib/oauth2/rfc6749/utils.py" />
        <File name="signals" src="pythonlib/oauthlib/signals.py" />
        <File name="uri_validate" src="pythonlib/oauthlib/uri_validate.py" />
        <File name="__init__" src="pythonlib/requests/__init__.py" />
        <File name="adapters" src="pythonlib/requests/adapters.py" />
        <File name="api" src="pythonlib/requests/api.py" />
        <File name="auth" src="pythonlib/requests/auth.py" />
        <File name="cacert" src="pythonlib/requests/cacert.pem" />
        <File name="certs" src="pythonlib/requests/certs.py" />
        <File name="compat" src="pythonlib/requests/compat.py" />
        <File name="cookies" src="pythonlib/requests/cookies.py" />
        <File name="exceptions" src="pythonlib/requests/exceptions.py" />
        <File name="hooks" src="pythonlib/requests/hooks.py" />
        <File name="models" src="pythonlib/requests/models.py" />
        <File name="README" src="pythonlib/requests/packages/README.rst" />
        <File name="__init__" src="pythonlib/requests/packages/__init__.py" />
        <File name="__init__" src="pythonlib/requests/packages/chardet/__init__.py" />
        <File name="big5freq" src="pythonlib/requests/packages/chardet/big5freq.py" />
        <File name="big5prober" src="pythonlib/requests/packages/chardet/big5prober.py" />
        <File name="chardetect" src="pythonlib/requests/packages/chardet/chardetect.py" />
        <File name="chardistribution" src="pythonlib/requests/packages/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="pythonlib/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="pythonlib/requests/packages/chardet/charsetprober.py" />
        <File name="codingstatemachine" src="pythonlib/requests/packages/chardet/codingstatemachine.py" />
        <File name="compat" src="pythonlib/requests/packages/chardet/compat.py" />
        <File name="constants" src="pythonlib/requests/packages/chardet/constants.py" />
        <File name="cp949prober" src="pythonlib/requests/packages/chardet/cp949prober.py" />
        <File name="escprober" src="pythonlib/requests/packages/chardet/escprober.py" />
        <File name="escsm" src="pythonlib/requests/packages/chardet/escsm.py" />
        <File name="eucjpprober" src="pythonlib/requests/packages/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="pythonlib/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrprober" src="pythonlib/requests/packages/chardet/euckrprober.py" />
        <File name="euctwfreq" src="pythonlib/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwprober" src="pythonlib/requests/packages/chardet/euctwprober.py" />
        <File name="gb2312freq" src="pythonlib/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="pythonlib/requests/packages/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="pythonlib/requests/packages/chardet/hebrewprober.py" />
        <File name="jisfreq" src="pythonlib/requests/packages/chardet/jisfreq.py" />
        <File name="jpcntx" src="pythonlib/requests/packages/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="pythonlib/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="pythonlib/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="pythonlib/requests/packages/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="pythonlib/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="pythonlib/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="pythonlib/requests/packages/chardet/langthaimodel.py" />
        <File name="latin1prober" src="pythonlib/requests/packages/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="pythonlib/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="pythonlib/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="pythonlib/requests/packages/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="pythonlib/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="pythonlib/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="pythonlib/requests/packages/chardet/sjisprober.py" />
        <File name="universaldetector" src="pythonlib/requests/packages/chardet/universaldetector.py" />
        <File name="utf8prober" src="pythonlib/requests/packages/chardet/utf8prober.py" />
        <File name="__init__" src="pythonlib/requests/packages/urllib3/__init__.py" />
        <File name="_collections" src="pythonlib/requests/packages/urllib3/_collections.py" />
        <File name="connection" src="pythonlib/requests/packages/urllib3/connection.py" />
        <File name="connectionpool" src="pythonlib/requests/packages/urllib3/connectionpool.py" />
        <File name="__init__" src="pythonlib/requests/packages/urllib3/contrib/__init__.py" />
        <File name="ntlmpool" src="pythonlib/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="pythonlib/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="exceptions" src="pythonlib/requests/packages/urllib3/exceptions.py" />
        <File name="fields" src="pythonlib/requests/packages/urllib3/fields.py" />
        <File name="filepost" src="pythonlib/requests/packages/urllib3/filepost.py" />
        <File name="__init__" src="pythonlib/requests/packages/urllib3/packages/__init__.py" />
        <File name="ordered_dict" src="pythonlib/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="six" src="pythonlib/requests/packages/urllib3/packages/six.py" />
        <File name="__init__" src="pythonlib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="pythonlib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="pythonlib/requests/packages/urllib3/poolmanager.py" />
        <File name="request" src="pythonlib/requests/packages/urllib3/request.py" />
        <File name="response" src="pythonlib/requests/packages/urllib3/response.py" />
        <File name="__init__" src="pythonlib/requests/packages/urllib3/util/__init__.py" />
        <File name="connection" src="pythonlib/requests/packages/urllib3/util/connection.py" />
        <File name="request" src="pythonlib/requests/packages/urllib3/util/request.py" />
        <File name="response" src="pythonlib/requests/packages/urllib3/util/response.py" />
        <File name="retry" src="pythonlib/requests/packages/urllib3/util/retry.py" />
        <File name="ssl_" src="pythonlib/requests/packages/urllib3/util/ssl_.py" />
        <File name="timeout" src="pythonlib/requests/packages/urllib3/util/timeout.py" />
        <File name="url" src="pythonlib/requests/packages/urllib3/util/url.py" />
        <File name="sessions" src="pythonlib/requests/sessions.py" />
        <File name="status_codes" src="pythonlib/requests/status_codes.py" />
        <File name="structures" src="pythonlib/requests/structures.py" />
        <File name="utils" src="pythonlib/requests/utils.py" />
        <File name="__init__" src="pythonlib/requests_oauthlib/__init__.py" />
        <File name="__init__" src="pythonlib/requests_oauthlib/compliance_fixes/__init__.py" />
        <File name="facebook" src="pythonlib/requests_oauthlib/compliance_fixes/facebook.py" />
        <File name="linkedin" src="pythonlib/requests_oauthlib/compliance_fixes/linkedin.py" />
        <File name="weibo" src="pythonlib/requests_oauthlib/compliance_fixes/weibo.py" />
        <File name="oauth1_auth" src="pythonlib/requests_oauthlib/oauth1_auth.py" />
        <File name="oauth1_session" src="pythonlib/requests_oauthlib/oauth1_session.py" />
        <File name="oauth2_auth" src="pythonlib/requests_oauthlib/oauth2_auth.py" />
        <File name="oauth2_session" src="pythonlib/requests_oauthlib/oauth2_session.py" />
    </Resources>
    <Topics />
</Package>
